import { GB, DE, ES, MX, MC, AU, NL, FI, FR, CA, JP, DK, TH, CN, US, IT } from 'country-flag-icons/react/3x2';

export const nationalityToFlag: { [key: string]: React.ComponentType<{ className?: string }> } = {
  British: GB,
  German: DE,
  Spanish: ES,
  Mexican: MX,
  Monegasque: MC,
  Australian: AU,
  Dutch: NL,
  Finnish: FI,
  French: FR,
  Canadian: CA,
  Japanese: JP,
  Danish: DK,
  Thai: TH,
  Chinese: CN,
  American: US,
  Italian: IT
};

export const constructorColors: { [key: string]: string } = {
  'Red Bull': 'border-[#3671C6]',
  'Mercedes': 'border-[#6CD3BF]',
  'Ferrari': 'border-[#F91536]',
  'McLaren': 'border-[#FF8700]',
  'Aston Martin': 'border-[#358C75]',
  'Alpine F1 Team': 'border-[#2293D1]',
  'Williams': 'border-[#37BEDD]',
  'AlphaTauri': 'border-[#5E8FAA]',
  'Alfa Romeo': 'border-[#C92D4B]',
  'Haas F1 Team': 'border-[#B6BABD]',
  // Legacy teams
  'Red Bull Racing': 'border-[#3671C6]',
  'Mercedes AMG': 'border-[#6CD3BF]',
  'Brawn GP': 'border-[#B0D915]',
  'Renault': 'border-[#FFF500]',
  'Racing Point': 'border-[#F596C8]',
  'Force India': 'border-[#FF5F0F]',
  'Toro Rosso': 'border-[#469BFF]',
  'Lotus F1': 'border-[#FFB800]',
  'Sauber': 'border-[#9B0000]',
  'Manor Marussia': 'border-[#323232]',
  'Marussia': 'border-[#6E0000]',
  'Caterham': 'border-[#016F37]',
  'HRT': 'border-[#B2945B]',
  'Virgin': 'border-[#F7051D]',
  'Toyota': 'border-[#CC1E1D]',
  'Super Aguri': 'border-[#D82E2E]',
  'Spyker': 'border-[#FF6E14]',
  'Midland': 'border-[#D82E2E]',
  'Jordan': 'border-[#FFC700]',
  'BAR': 'border-[#D82E2E]',
  'Minardi': 'border-[#000000]',
  'Jaguar': 'border-[#316E35]',
  'Prost': 'border-[#0F1FDB]',
  'Arrows': 'border-[#FF8700]',
}; 